version: 2

registries:
  maven-google:
    type: maven-repository
    url: https://dl.google.com/dl/android/maven2/
    username: ""
    password: ""

updates:
  - package-ecosystem: "gradle"
    directory: "/"
    registries:
      - maven-google
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "Versions"
    reviewers:
      - "Jeffset"
    groups:
      kotlin:
        patterns:
          - "org.jetbrains.dokka:*"
          - "org.jetbrains.kotlin:*"
          - "com.google.devtools.ksp:*"
      libs:
        patterns: [ "*" ]
        exclude-patterns:
          - "org.jetbrains.dokka:*"
          - "org.jetbrains.kotlin:*"
          - "com.google.devtools.ksp:*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "CI"
    reviewers:
      - "Jeffset"
    groups:
      actions:
        patterns: [ "*" ]
