name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Java
        uses: actions/setup-java@v1.4.3
        with:
          java-version: '11'
          java-package: jdk
          architecture: x64

      - name: Checkout
        uses: actions/checkout@v3

      - name: Check
        uses: gradle/gradle-build-action@v2
        with:
          arguments: check --no-configuration-cache --stacktrace
